"""agregar campos de puesto y proyecto al usuario

Revision ID: 58f680d497ba
Revises: 5aefc105e6b1
Create Date: 2026-02-17 13:05:42.568266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f680d497ba'
down_revision = '5aefc105e6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puesto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('proyecto_actual', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cargo_jefe', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cargo_jefe')
        batch_op.drop_column('proyecto_actual')
        batch_op.drop_column('puesto')

    # ### end Alembic commands ###
