"""tabla bitacora

Revision ID: 5aefc105e6b1
Revises: 8c4eca0deb4c
Create Date: 2026-02-17 12:31:56.260696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aefc105e6b1'
down_revision = '8c4eca0deb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('empresa', sa.String(length=100), nullable=False),
    sa.Column('puesto', sa.String(length=100), nullable=False),
    sa.Column('periodo_semanal', sa.String(length=100), nullable=False),
    sa.Column('nombre_jefe_inmediato', sa.String(length=100), nullable=False),
    sa.Column('cargo_jefe_inmediato', sa.String(length=100), nullable=False),
    sa.Column('proyecto_actual', sa.String(length=200), nullable=False),
    sa.Column('actividades', sa.Text(), nullable=False),
    sa.Column('herramientas_utilizadas', sa.String(length=200), nullable=True),
    sa.Column('entregable_generado', sa.String(length=200), nullable=True),
    sa.Column('direccion_url', sa.String(length=500), nullable=True),
    sa.Column('incidencias', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitacoras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitacoras_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacoras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitacoras_timestamp'))

    op.drop_table('bitacoras')
    # ### end Alembic commands ###
