"""cambio status y medio entregable

Revision ID: e60529603225
Revises: 58f680d497ba
Create Date: 2026-02-19 16:18:17.856329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e60529603225'
down_revision = '58f680d497ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacoras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('medio_entregable', sa.Text(), nullable=True))
        batch_op.drop_column('direccion_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacoras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('medio_entregable')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
